Add stylesheet attribute
unyt-org/uix pull request #61
Opened 2024-01-17 12:18 UTC by benStre

See https://github.com/unyt-org/uix-dom/issues/4

2024-01-18 08:00 UTC, jonasstrehle requested changes

2024-01-18 08:00 UTC, jonasstrehle commented on src/server/server.ts
>          if (url.searchParams.has("scope") && (url.ext === "scss" || url.ext === "css") && filepath.fs_exists) {
Should we consider to update all `fs_exist` usages to use async non blocking logic instead? Might improve performance when scaling. What do you think abou that @benStre?

2024-01-18 14:12 UTC, benStre commented on src/server/server.ts
>          if (url.searchParams.has("scope") && (url.ext === "scss" || url.ext === "css") && filepath.fs_exists) {
Sounds reasonable

2024-01-19 22:29 UTC, jonasstrehle approved these changes

2024-01-19 23:34 UTC, merged